# Generated by Django 5.1.6 on 2025-02-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_case_index_alter_activity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('sugerencia_1', models.CharField(blank=True, max_length=255, null=True)),
                ('puntaje_1', models.IntegerField(blank=True, null=True)),
                ('material_code_sugerencia_1', models.CharField(max_length=255)),
                ('sugerencia_2', models.CharField(blank=True, max_length=255, null=True)),
                ('puntaje_2', models.IntegerField(blank=True, null=True)),
                ('sugerencia_3', models.CharField(blank=True, max_length=255, null=True)),
                ('puntaje_3', models.IntegerField(blank=True, null=True)),
                ('producto_nuevo', models.BooleanField()),
                ('material_code', models.CharField(blank=True, max_length=255, null=True)),
                ('predicciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
