# Generated by Django 5.1.6 on 2025-02-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_material_delete_activity_delete_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_code', models.CharField(blank=True, max_length=255, null=True)),
                ('material_name', models.CharField(max_length=255)),
                ('current_stock', models.IntegerField()),
                ('is_free_text', models.BooleanField()),
                ('unit_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('material_code', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('costumer_id', models.CharField(max_length=10)),
                ('costumer_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('is_free_text', models.BooleanField()),
            ],
        ),
    ]
